[[constraint]]
  branch = "master"
  name = "github.com/milosgajdos83/matrix"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "gocv.io/x/gocv"
  version = "0.19.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/exp"

[[constraint]]
  branch = "master"
  name = "gonum.org/v1/gonum"

[[constraint]]
  branch = "master"
  name = "gonum.org/v1/plot"

[prune]
  go-tests = true
  unused-packages = true
